### PR TITLE
resolver: automatically trim whitespace from strings

### PR DESCRIPTION
**Pull request by danielhochman**
### Description
Automatically trim whitespace from any string values for resolver input.

From internal chat:

>UX suggestion - at least for the resize ASG workflow, any leading/trailing whitespace in the “search by name” form input leads to a “not found” error, which is something one can run into when copy/pasting ASG names around and fat-fingering selection. What about sanitizing the input somehow by trimming leading/trailing whitespace?

### Testing Performed
Manual

### CODE REVIEW

**Comment by danielhochman** [comment]
@dschaller opened as draft, let me know what you think of this approach.

**Review by dschaller — APPROVED** [review]
Generally looks good to me. It would be awesome if we had the text field component configurable to trim leading and trailing whitespace such that the user can see it and it'll be safe for any values (e.g. this won't handle nested dicts at the moment) but that can happen at a later point

**Comment by danielhochman** [comment]
@dschaller i thought about that but i think for it to work as expected it would need to be done on focus change and on submit which is pretty complicated. i will open a follow-up issue for that type of field prop enhancement.

**Comment by danielhochman** [comment]
filed https://github.com/lyft/clutch/issues/450

**Pull request merged**
