### PR TITLE
k8s: add pod status string to pod proto

### PR DESCRIPTION
**Pull request by rithujohn191**
### Description
This PR adds a status string to the pod definition that represents the overall status of the pod calculated by looking at the statuses of its containers. This summary status string is important as it reflects the true status of the pod unlike the `State` field which is just a high level overview of the pod-lifecycle.

This code has been referenced from the upstream dashboard: https://github.com/kubernetes/dashboard/pull/5660

### Testing Performed
-local
-unit

### CODE REVIEW

**Review by danielhochman — COMMENTED** [review]
looks great! can we put together some more test coverage?

also does this match or differ from the lyftkube output (not sure if lyftkube is purely kubectl for the status column).

**Comment by rithujohn191** [comment]
@danielhochman yea this matches lyftkube output directly (which is mostly kubectl for the status column). Will add in more tests

**Comment by rithujohn191** [comment]
added more unit tests to cover different pod states

**Review by smonero — APPROVED** [review]

**Comment by rithujohn191** [comment]
@danielhochman added in extra test cases to cover different pod states

**Review by scarlettperry — APPROVED** [review]

**Pull request merged**
