### PR TITLE
experimentation: Increasing termination reason length to fit the reason

### PR DESCRIPTION
**Pull request by kathan24**
### Description

This PR increases the length of the termination reason field in the experiments. PR also has the migration script so that we can migrate the schema changes. 

### GitHub Issue

Fixes #

### CODE REVIEW

**Review by Augustyniak — COMMENTED** [review]
You still need to modify a proto in here https://github.com/lyft/clutch/blob/main/api/chaos/experimentation/v1/experimentation.proto#L73

**Review by Augustyniak — APPROVED** [review]

**Comment by kathan24** [comment]
🚀

**Comment by kathan24** [comment]
🚀

**Comment by kathan24** [comment]
💨

**Pull request merged**
