### PR TITLE
Frontend: Add set height for Card component

### PR DESCRIPTION
**Pull request by jecr**
### Description
Card components in the landing page adjusted their height according to the card's description length. That caused disparity in the cards sizes. This update sets the Card height to a fixed 214px.

Before:
image

After:
image

### Testing Performed
manual

### CODE REVIEW

**Comment by smonero** [comment]
what happens if the text is too long to fit inside the card? As in, if there is a super long description or title could that cause problems?

**Comment by jecr** [comment]
> what happens if the text is too long to fit inside the card? As in, if there is a super long description or title could that cause problems?

image
The text will get cut at the card's max-height and some of if will be left out of view, I tried getting the nested elements to max out at the card's height using flexbox, in order to add `text-overflow: ellipsis`, but I couldn't prevent the inner elements from overflowing.

**Comment by jdslaugh** [comment]
> 

So looking into this a bit, it looks like adding ellipsis is rather difficult through pure CSS for multiline text. So we have two options, set a maximum length and truncate it manually using `substring` or we can try doing it via css `line-clamp`.

To do that you would add a styled component to the typography and do something like this:

```
const TruncatedText = styled(Typography)({
  display: "-webkit-box",
  "-webkit-box-orient": "vertical",
  "-webkit-line-clamp": "3",
});
...
          <TruncatedText color="rgba(13, 16, 48, 0.6)" variant="body2">
            {description}
          </TruncatedText>
```

We'll need to verify this works in multiple browsers before implementing, however I think it's the cleanest and most extensible variation.

**Comment by jecr** [comment]
Added @jdslaugh's suggested wrapper for Typography the description. According to MDN it has [full support](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) in browsers.

image

**Review by smonero — APPROVED** [review]

**Review by jdslaugh — APPROVED** [review]

**Pull request merged**
