### PR TITLE
Create dependabot.yml #25

### PR DESCRIPTION
**Pull request by jarz**
Created a basic `dependabot.yml` configuration for frontend and backend code. #25 

After merging, dependabot should create a new PR rather quickly wanting to upgrade lodash.

### CODE REVIEW

**Comment by dschaller** [comment]
Awesome! Thanks for the contribution @jarz

**Comment by dschaller** [comment]
Since we can't specify multiple directories for npm/gomod should we run these from the root to check for npm/go dependency updates in both the source code as well as the documentation code?

**Comment by jarz** [comment]
@dschaller according to [docs](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#directory) it's going to look for the `package.json` and `go.mod` files in the directory specified.

I'll update my branch and see how dependabot reacts to multiple entries for the `package-ecosystem`.

**Comment by dschaller** [comment]
It looks like you can have duplicate ecosystem entries: https://github.com/kobylynskyi/graphql-java-codegen/blob/master/.github/dependabot.yml. I confirmed there were dependabot PRs for the unique entries.

Can you update to add another ecosystem for gomod to update `/docs/_website/generator`?

**Pull request merged**
