### PR TITLE
ui v2: right align button groups by default

### PR DESCRIPTION
**Pull request by dschaller**
### Description

Right justify all button groups on details pages.

### CODE REVIEW

**Comment by danielhochman** [comment]
can we make this the default for ButtonGroup?

**Comment by dschaller** [comment]
We can but I'd think that by default a button group would grow from the left or center.

**Comment by danielhochman** [comment]
in clutch i'm pretty sure all buttons are right aligned though, aren't they?

another way to do it would be to apply the flex property from the step to any children with the button groups class

**Comment by dschaller** [comment]
I think for the most part yes. I guess the one place I'm thinking of it the experimentation code that might have centered buttons at the moment but we can shift these to default to right since it'll match the workflows. Will change the default

**Review by danielhochman — APPROVED** [review]

**Pull request merged**
